### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by malteos** [ryabhmd/scilons-eval#4]
Thanks for sharing this! 

A few things I noticed while browsing the repo:
- Use AutoTokenizer and AutoModelForTokenClassification to support other model types https://github.com/ryabhmd/scilons-eval/blob/main/model_eval.py#L30
- no need to assign the model to a device, trainer takes care about this https://github.com/ryabhmd/scilons-eval/blob/main/model_eval.py#L31 
- you can make custom trainer class and override the evaluate with your own eval logic and the results are also saved to wandb, like in https://github.com/malteos/scincl/blob/main/gdt/scidocs_trainer.py#L46
- you can use the HF argparser to make all training args available as cli args, see https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py#L250
- what LR settings did you use? The difference could explain the different scores compared to the paper

See this more as a recommendation or nice to have ;-)

**Comment by ryabhmd** [comment]
Thanks Malte! 
I took all your feedback into account and amended the script except for overriding the evaluation code, I will keep that in mind but will close the issue for now. :)
